version: "3"

services:
  # sidetree-core:
  #   build: ./packages/sidetree-core
  #   ports:
  #     - "3000:3000"
  # sidetree-ipfs:
  #   build: ./packages/sidetree-ipfs
  #   ports:
  #     - "3001:3001"
  sidetree-ethereum:
    build: ./packages/sidetree-ethereum-v2
    ports:
      - "3002:3002"
    env_file:
      - ./packages/sidetree-ethereum-v2/docker.env
    links:
      - "ganache:ganache"
  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    volumes:
    - ./ganache_data:/ganache_data
    entrypoint:
      - node
      - ./build/cli.node.js
      - --deterministic
      - --db=/ganache_data
      - --mnemonic
      - 'weird ensure parent humor crawl doctor machine narrow subway bleak panel worth'
      - --networkId
      - '5777'
      - --hostname
      - '0.0.0.0'
      - --debug


