version: '3'

services:

  mongo:
    image: mongo:3.7-xenial

  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - "./dist:/app/dist"
    depends_on:
      - mongo
    command: yarn start:dev
